acme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.urls import re_path
from . import views

handler404 = 'acme.views.handler404'
handler500 = 'acme.views.handler500'

urlpatterns = [
	
	re_path(r'^$',views.home, name='home'),
    path('admin/', admin.site.urls),
    re_path(r'^blog/',include('blog.urls'))
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^posts/(?P<id>[0-9]+)$', views.show, name='show')
	]
	

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length=255)
	body = models.TextField()
	
	def __str(self):
		return self.title

acme/views.py
#from django.http import HttpResponse
from django.shortcuts import render
def home (request):
	#return HttpResponse('HEllo acme')
	return render(request,'pages/home.html')

def handler404(request, exception):
	return render(request, 'errors/404.html', {'error':exception}, status=404)

def handler500(request, exception=None):
	return render(request, 'errors/500.html', {'error':exception}, status=500)
	#handler 500

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post

# Create your views here.

def index(request):
	posts= Post.objects.all()
	return render(request,'blog/index.html',{'posts':posts})

def show(request, id):
	post = get_object_or_404(Post, pk=id)
	return render (request,'blog/show.html', {'post':post})

blog/templates/blog/index.html
{% block content %} 
<h1> coucou</h1>
<h1>Blog ({{posts|length}}) blog</h1>

<ul>
{% for post in posts%}
	<li>{{post}}</li>
{% endfor %}
</ul>
{% endblock %}

blog/templates/blog/show.html
<h1>Show post id : {{post.id}}</h1>
<h1>Show post title {{post.title}}</h1>
<h1>Show post body {{post.body}}</h1>

templates/layouts/_footer.html
<footer>
	<p> copyright mon footer {% now 'Y' %}</p>
</footer>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

	<title>acme</title>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css'%}">
</head>
<body>
{% block content %} {% endblock %}


</body>
</html>

templates/pages/home.html
<h1>Hello ACME from home</h1>
<p> <a href="{% url 'blog:index' %}">Visiter notre blog</a></p>